name: Snyk
on:
  workflow_dispatch:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Container image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Run Snyk
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: localbuild/testimage:latest

